{ lib, fetchFromGitHub, buildNpmPackage, swagger-codegen3, stdenvNoCC, ... }:
let

  pname = "hydra-js";
  version = "0.0.1";

  meta = with lib; {
    homepage = "https://github.com/NixOS/hydra";
    description =
      "Autogenerated nodejs code to interact with the official Hydra API spec";
    license = licenses.gpl3;
  };

  autogenerated-ts = stdenvNoCC.mkDerivation rec {
    inherit pname version meta;

    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "hydra";
      # Master here is inentionally unstable to ensure we capture any possible 
      # changes to the hydra solution 
      rev = "master";
      hash = "sha256-5q/7yz6jJedD8YU3SuYyXtN3qEAlOBRKGZxOcYt/0X8=";
    };

    phases = [ "buildPhase" "fixupPhase" ];

    buildPhase = ''
      mkdir -p $out
      ${swagger-codegen3}/bin/swagger-codegen3 generate -i ${src}/hydra-api.yaml -l typescript-axios -o $out
      ln -s ${autogenerated-ts-lock}/package-lock.json $out/package-lock.json
    '';
  };

  autogenerated-ts-lock = stdenvNoCC.mkDerivation rec {
    inherit pname version meta;
    src = ./.;
    phases = [ "unpackPhase" "installPhase" ];
    installPhase = ''
      mkdir -p $out
      cp $src/package-lock.json $out/package-lock.json
    '';
  };

  npmDepsHash = "sha256-VDhDfsAKpQp+GqV38+U4SAYL4wXguCR1r/+TRAi8wDI=";

in buildNpmPackage {
  inherit pname version meta npmDepsHash;
  src = autogenerated-ts;
}
