# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "AsyncFixer";
    version = "1.6.0";
    sha256 = "0li4wjihc0cbmz5v6206vbc3flzfnqi026dwp3ldk8pj8h79zigh";
  })
  (fetchNuGet {
    pname = "AutoMapper";
    version = "11.0.1";
    sha256 = "1z1x5c1dkwk6142km5q6jglhpq9x82alwjjy5a72c8qnq9ppdfg3";
  })
  (fetchNuGet {
    pname = "ByteSize";
    version = "2.1.1";
    sha256 = "0v2bdldyafgswv96jf38jr2rrs69wjv5h2s489yp2ps36z9qxy34";
  })
  (fetchNuGet {
    pname = "Devlooped.SponsorLink";
    version = "0.10.5";
    sha256 = "0d78fgc6xrrvnjk5wrbwr86hhrkd4i5fz02c4v7kyz12pyw85rwv";
  })
  (fetchNuGet {
    pname = "ErrorProne.NET.Structs";
    version = "0.1.2";
    sha256 = "1wl03zrpik0spqca4q20y5cxmbb4jw2vahm2yyblz3xqxnlk6j87";
  })
  (fetchNuGet {
    pname = "HexMate";
    version = "0.0.3";
    sha256 = "1gpj4nx05lknvnnfhcc4kc1wdmrs9vkw3sbb6qbj5m7ygm8g03x4";
  })
  (fetchNuGet {
    pname = "Intellenum";
    version = "1.0.0-beta.3";
    sha256 = "1z3mwrxshd5wwxwwifgg2c1lnkds5xsjcqribacxqh3g1i5xglhm";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2022.1.0";
    sha256 = "0lsqpssain0v9i3jhpi1c42r5s329y31cvqk5x7gqvy17f29y002";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.BannedApiAnalyzers";
    version = "3.3.4";
    sha256 = "1vzrni7n94f17bzc13lrvcxvgspx9s25ap1p005z6i1ikx6wgx30";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.5.0";
    sha256 = "01i28nvzccxbqmiz217fxs6hnjwmd5fafs37rd49a6qp53y6623l";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Abstractions";
    version = "6.34.0";
    sha256 = "0dgn51k142f73l6fk4bsqrpwqhcw6s8y98548kczbzy7qxcnyp82";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.JsonWebTokens";
    version = "6.34.0";
    sha256 = "0c01dqya958z9ypf0155aqdkvkz9j4j5mgnygxzkisri2cs2w7gs";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Logging";
    version = "6.34.0";
    sha256 = "0fm4nrihhqn4wrcj2q06rzfrfzgzilb7ch3izkv89c4q74x0yhkb";
  })
  (fetchNuGet {
    pname = "Microsoft.IdentityModel.Tokens";
    version = "6.34.0";
    sha256 = "1vkjwryz4wdsaawfq3r80qrmfiyv2zp9y6fzkf2014sqw4nf1vwl";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    sha256 = "193xwf33fbm0ni3idxzbr5fdq3i2dlfgihsac9jj7whj0gd902nh";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "16.9.60";
    sha256 = "0dbhm4n3fhfa55gpisgl3vxfc29a47hi47sqvqn5qxd7484bciyn";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "NStack.Core";
    version = "0.17.1";
    sha256 = "18xf6zcllmzsz3dx77igdrr4239n8bwdk8i7nkrdrn8b1jnq0nxi";
  })
  (fetchNuGet {
    pname = "protobuf-net";
    version = "3.2.16";
    sha256 = "0pwlqlq2p8my2sr8b0cvdav5cm8wpwf3s4gy7s1ba701ac2zyb9y";
  })
  (fetchNuGet {
    pname = "protobuf-net.Core";
    version = "3.2.16";
    sha256 = "00znhikq7valr3jaxg66cwli9hf75wkmmpf6rf8p790hf8lxq0c5";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    sha256 = "1cqh1sv3h5j7ixyb7axxbdkqx6cxy00p4np4j91kpm492rf4s25b";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    sha256 = "0aqqi1v4wx51h51mk956y783wzags13wa7mgqyclacmsmpv02ps3";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    sha256 = "15hgf6zaq9b8br2wi1i3x0zvmk410nlmsmva9p0bbg73v6hml5k4";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    sha256 = "1jx02q6kiwlvfksq1q9qr17fj78y5v6mwsszav4qcz9z25d5g6vk";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "0.44.0";
    sha256 = "0vsyvcmrg6k7938a3fqchynwkrcyipcgwl9i18hmimwihv8x0l4f";
  })
  (fetchNuGet {
    pname = "SteamKit2";
    version = "2.5.0-beta.1";
    sha256 = "0691285g4z12hv5kpv72l36h45086n14rw56x3dnixcvrjzg2q01";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "7.0.0";
    sha256 = "1n9122cy6v3qhsisc9lzwa1m1j62b8pi2678nsmnlyvfpk0zdagm";
  })
  (fetchNuGet {
    pname = "System.IdentityModel.Tokens.Jwt";
    version = "6.34.0";
    sha256 = "150ybq4ba9sm3c37d758ngja6wz72f0840d8vfs6bhy6pw0svzwy";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    sha256 = "04r1lkdnsznin0fj4ya1zikxiqr0h6r6a1ww2dsm60gqhdrf0mvx";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    sha256 = "066ixvgbf2c929kgknshcxqj6539ax7b9m570cp8n179cpfkapz7";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.5.0";
    sha256 = "1pm4ykbcz48f1hdmwpia432ha6qbb9kbrxrrp7cg3m8q8xn52ngn";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    sha256 = "1f04lkir4iladpp51sdgmis9dj4y8v08cka0mbmsy0frc9a4gjqr";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "4.7.2";
    sha256 = "0ap286ykazrl42if59bxhzv81safdfrrmfqr3112siwyajx4wih9";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "4.7.2";
    sha256 = "10xj1pw2dgd42anikvj9qm23ccssrcp7dpznpj4j7xjp1ikhy3y4";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    sha256 = "00k8ja51d0f9wrq4vv5z2jhq8hy31kac2rg0rv06prylcybzl8cy";
  })
  (fetchNuGet {
    pname = "Terminal.Gui";
    version = "1.7.2";
    sha256 = "187dz9vfwjs2n3lak7zjr0njihmvxdiwx9128kjasdgw883kdpma";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.2.14";
    sha256 = "15awsgyha0h1gnjnsciqvih53igh7x9fr09vjwbxydkm3r7na7sb";
  })
  (fetchNuGet {
    pname = "Wcwidth";
    version = "1.0.0";
    sha256 = "02i3m8vrpanzj1h4n8zj4dnd3cndx6cmg36n9qj56waa18d6mqy1";
  })
]
