{
 "title": "Nextcloud",
 "tags": [
  "services",
  "filesystem"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "description": "current service state",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"nextcloud\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "max(nextcloud_system_info{job=\"nextcloud\"}) by (host, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_database_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "max(nextcloud_database_info{job=\"nextcloud\"}) by (host, version, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users: Last Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_active_users_daily_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users: Last Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "nextcloud_active_users_daily_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users: Last Hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_active_users_hourly_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users: Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "nextcloud_active_users_hourly_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_files_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nextcloud_files_total{job=\"nextcloud\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}