{
 "title": "ZFS",
 "tags": [ "disks" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(zpool_stats_size,host)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zpool_stats_size{host=\"$host\", vdev=\"root\"},name)"
    }
   },
   {
    "name": "vdev",
    "label": "VDEV",
    "query": {
     "query": "label_values(zpool_stats_size{name=~\"$pool\"},vdev)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Zpool stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zpool",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_size{host=\"$host\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "size"
    },
    {
     "expr": "zpool_stats_alloc{host=\"$host\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "zpool_stats_free{host=\"$host\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "free"
    },
    {
     "expr": "(zpool_stats_alloc{host=\"$host\",name=~\"$pool\",vdev=~\"root\"} /\nzpool_stats_size{host=\"$host\",name=~\"$pool\",vdev=~\"root\"}) * 100",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_bytes{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_bytes{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_ops{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_ops{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_errors{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_errors{host=\"$host\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "VDEV stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VDEV",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_size{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}",
     "legendFormat": "size"
    },
    {
     "expr": "zpool_stats_alloc{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "zpool_stats_free{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}",
     "legendFormat": "free"
    },
    {
     "expr": "(zpool_stats_alloc{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"} /\nzpool_stats_size{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}) * 100",
     "legendFormat": "capacity"
    },
    {
     "expr": "zpool_stats_fragmentation{host=\"$host\",name=~\"$pool\",vdev=\"$vdev\"}",
     "legendFormat": "fragmentation"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_bytes{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_bytes{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_ops{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_ops{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_errors{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_errors{host=\"$host\",name=~\"$pool\",vdev=~\"$vdev\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Volume stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volumes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_fragmentation{host=\"$host\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "fragmentation"
    },
    {
     "expr": "zpool_stats_checksum_errors{host=\"$host\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "checksum errors"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_bytes{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_bytes{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_ops{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_ops{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_errors{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_write_errors{host=\"$host\",name=~\"$pool\",path!=\"\"}[$__rate_interval])) without (state)",
     "legendFormat": "{{ name }} - {{ vdev }}"
    }
   ]
  },
  {
   "title": "Scan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Finished",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_start_ts{host=\"$host\",name=~\"$pool\",state=\"finished\"} * 1000",
     "legendFormat": "start time"
    },
    {
     "expr": "zpool_scan_stats_end_ts{host=\"$host\",name=~\"$pool\",state=\"finished\"} * 1000",
     "legendFormat": "end time"
    },
    {
     "expr": "zpool_scan_stats_examined{host=\"$host\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "scanned"
    },
    {
     "expr": "zpool_scan_stats_processed{host=\"$host\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "repaired"
    },
    {
     "expr": "zpool_scan_stats_errors{host=\"$host\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Ongoing",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_start_ts{host=\"$host\",name=~\"$pool\",state!=\"finished\"} * 1000",
     "legendFormat": "start time"
    },
    {
     "expr": "zpool_scan_stats_rate{host=\"$host\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "rate"
    },
    {
     "expr": "zpool_scan_stats_errors{host=\"$host\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "errors"
    },
    {
     "expr": "zpool_scan_stats_to_examine{host=\"$host\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "to scan"
    },
    {
     "expr": "zpool_scan_stats_to_process{host=\"$host\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "to repair"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_rate{host=\"$host\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "{{ name }} - {{ function }}"
    }
   ]
  },
  {
   "title": "ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ARC size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_arcstats_size{host=\"$host\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "zfs_arcstats_c{host=\"$host\"}",
     "legendFormat": "target"
    },
    {
     "expr": "zfs_arcstats_data_size{host=\"$host\"}",
     "legendFormat": "data"
    },
    {
     "expr": "zfs_arcstats_metadata_size{host=\"$host\"}",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "ARC - hit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(zfs_arcstats_demand_data_hits{host=\"$host\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_demand_data_hits{host=\"$host\"}[$__rate_interval]) +\nrate(zfs_arcstats_demand_data_misses{host=\"$host\"}[$__rate_interval])\n) * 100",
     "legendFormat": "data"
    },
    {
     "expr": "rate(zfs_arcstats_demand_metadata_hits{host=\"$host\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_demand_metadata_hits{host=\"$host\"}[$__rate_interval]) +\nrate(zfs_arcstats_demand_metadata_misses{host=\"$host\"}[$__rate_interval])\n) * 100",
     "legendFormat": "metadata"
    }
   ]
  },
  {
   "title": "MRU",
   "type": "timeseries",
   "description": "Most Recently Used cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(zfs_arcstats_mru_hits{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(zfs_arcstats_mru_ghost_hits{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "ghost hits"
    }
   ]
  },
  {
   "title": "MFU",
   "type": "timeseries",
   "description": "Most Frequently Used cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(zfs_arcstats_mfu_hits{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(zfs_arcstats_mfu_ghost_hits{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "ghost hits"
    }
   ]
  },
  {
   "title": "L2 ARC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "targets": [
    {}
   ]
  },
  {
   "title": "L2 ARC size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zfs_arcstats_l2_size{host=\"$host\"}",
     "legendFormat": "actual"
    },
    {
     "expr": "zfs_arcstats_l2_hdr_size{host=\"$host\"}",
     "legendFormat": "hdr"
    }
   ]
  },
  {
   "title": "ARC - hit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(zfs_arcstats_l2_hits{host=\"$host\"}[$__rate_interval]) /\n(\nrate(zfs_arcstats_l2_hits{host=\"$host\"}[$__rate_interval]) +\nrate(zfs_arcstats_l2_misses{host=\"$host\"}[$__rate_interval])\n) * 100",
     "legendFormat": "hit"
    }
   ]
  },
  {
   "title": "IO size - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "repeat": "pool",
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_sync_read_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sync Write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_sync_write_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Async Read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_async_read_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Async Write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_async_write_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Scrub",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_scrub_read_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Trim",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_io_size_trim_write_ind{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Latency - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "repeat": "pool",
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_total_read{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Total Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_total_read{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_disk_read{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_disk_write{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Sync Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_sync_read{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Sync Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_sync_write{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Async Read Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_async_read{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Async Write Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_async_write{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Scrub",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_scrub{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Trim",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(zpool_latency_trim{host=\"$host\",name=\"$pool\",vdev=\"root\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "ZIO queue - $pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 209 },
   "repeat": "pool",
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "targets": [
    {
     "expr": "zpool_vdev_queue_sync_r_active{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "zpool_vdev_queue_sync_r_pend{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Sync Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "targets": [
    {
     "expr": "zpool_vdev_queue_sync_w_active{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "zpool_vdev_queue_sync_w_pend{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Async Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "targets": [
    {
     "expr": "zpool_vdev_queue_async_r_active{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "zpool_vdev_queue_async_r_pend{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Async Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "targets": [
    {
     "expr": "zpool_vdev_queue_async_w_active{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "zpool_vdev_queue_async_w_pend{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Scrub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
   "targets": [
    {
     "expr": "zpool_vdev_queue_async_scrub_active{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "active"
    },
    {
     "expr": "zpool_vdev_queue_async_scrub_pend{host=\"$host\",name=\"$pool\"}",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}