version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "staging"
    open-pull-requests-limit: 1
    reviewers:
      - "JayRovacsek"
