# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "AsyncFixer";
    version = "1.6.0";
    hash = "sha256-8MWfDkTyotnouLwZASK27lM32NoGCLPLr4sBBqPkJFI=";
  })
  (fetchNuGet {
    pname = "ByteSize";
    version = "2.1.1";
    hash = "sha256-ZPiO0zdDX3F9QkQLWLbkyeicRZZoOGnS5vo55RttS2w=";
  })
  (fetchNuGet {
    pname = "Devlooped.SponsorLink";
    version = "0.10.5";
    hash = "sha256-m+eCuL8ifD/PJkyA70okbWYIDcp8ZV6mtDvnbthz6DQ=";
  })
  (fetchNuGet {
    pname = "ErrorProne.NET.Structs";
    version = "0.1.2";
    hash = "sha256-B0kzqe24j0+X96JCtQWXZK3aWfFAYKIYvhrMePMfgPI=";
  })
  (fetchNuGet {
    pname = "HexMate";
    version = "0.0.3";
    hash = "sha256-pA/wUH3+1CIXNmvpwedOOtfGA5uEMeis3XbSArol8r4=";
  })
  (fetchNuGet {
    pname = "Intellenum";
    version = "1.0.0-beta.3";
    hash = "sha256-FdLXSwxvQNyZWjFjJnUvuk1LAxPvuch557w0qHvmdfw=";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2022.1.0";
    hash = "sha256-AgCfhDvBb/xOLxNvFoZPYuiSBWEhXihHTBvYqLS+WFM=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.BannedApiAnalyzers";
    version = "3.3.4";
    hash = "sha256-YPTHTZ8xRPMLADdcVYRO/eq3O9uZjsD+OsGRZE+0+e8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    hash = "sha256-Enknv2RsFF68lEPdrf5M+BpV1kHoLTVRApKUwuk/pj0=";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "2.2.0";
    hash = "sha256-qm/4W4SRTSkLHvNuIB51PBRIPymia43JyRjH5FUOXFk=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "16.9.60";
    hash = "sha256-1ke2CCKndVws3lgfEuEhKgnm+h706XhfKcpBNyypcDU=";
  })
  (fetchNuGet {
    pname = "NStack.Core";
    version = "0.17.1";
    hash = "sha256-sVuArQwL2dzytCei2fhCNg1Bcm4vntPb+PpXStk3rqM=";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "7.2.3";
    hash = "sha256-m42R1BjEEyNZR/AxEHXQCmO3y03PmXAdtUXiWJokmsc=";
  })
  (fetchNuGet {
    pname = "Spectre.Console";
    version = "0.49.2-preview.0.67";
    hash = "sha256-e1BrfX8ME8Ob7ZVKx8VYExKNvLzHHxNJ1R+Yv2lVE3A=";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "1.0.0";
    hash = "sha256-Om2PRAfm4LoPImty4zpGo/uoqha6ZnuCU6iNcAvKiUE=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    hash = "sha256-UemDHGFoQIG7ObQwRluhVf6AgtQikfHEoPLC6gbFyRo=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.5";
    hash = "sha256-NKWNrCcKy8S5ldsJzm6+udU53fWzmPGZZG/gpk0Kz4k=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    hash = "sha256-niH6l2fU52vAzuBlwdQMw0OEoRS/7E1w5smBFoqSaAI=";
  })
  (fetchNuGet {
    pname = "Terminal.Gui";
    version = "1.7.2";
    hash = "sha256-qt42B0L8Na3kRCKkzmPru8IoLcjyn6nosEJL7nb67aA=";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.2.14";
    hash = "sha256-Sx9lTx51Nt8XlzuB7FI/8MVRYNw4Mm2lfQECBf3TXJU=";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.4.3";
    hash = "sha256-w08VairCkCh9bL+/0cb775HDZjWAjL8ZsxyMjpyStEM=";
  })
  (fetchNuGet {
    pname = "Wcwidth";
    version = "1.0.0";
    hash = "sha256-weNqGgpKcVMkTtaMV5npzbLRbCPyI0tgkN+qmzeqIwo=";
  })
]
