# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "AsyncFixer";
    version = "1.6.0";
    sha256 = "0li4wjihc0cbmz5v6206vbc3flzfnqi026dwp3ldk8pj8h79zigh";
  })
  (fetchNuGet {
    pname = "ByteSize";
    version = "2.1.1";
    sha256 = "0v2bdldyafgswv96jf38jr2rrs69wjv5h2s489yp2ps36z9qxy34";
  })
  (fetchNuGet {
    pname = "Devlooped.SponsorLink";
    version = "0.10.5";
    sha256 = "0d78fgc6xrrvnjk5wrbwr86hhrkd4i5fz02c4v7kyz12pyw85rwv";
  })
  (fetchNuGet {
    pname = "ErrorProne.NET.Structs";
    version = "0.1.2";
    sha256 = "1wl03zrpik0spqca4q20y5cxmbb4jw2vahm2yyblz3xqxnlk6j87";
  })
  (fetchNuGet {
    pname = "HexMate";
    version = "0.0.3";
    sha256 = "1gpj4nx05lknvnnfhcc4kc1wdmrs9vkw3sbb6qbj5m7ygm8g03x4";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2022.1.0";
    sha256 = "0lsqpssain0v9i3jhpi1c42r5s329y31cvqk5x7gqvy17f29y002";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.WebUtilities";
    version = "2.2.0";
    sha256 = "0cs1g4ing4alfbwyngxzgvkrv7z964isv1j9dzflafda4p0wxmsi";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.BannedApiAnalyzers";
    version = "3.3.4";
    sha256 = "1vzrni7n94f17bzc13lrvcxvgspx9s25ap1p005z6i1ikx6wgx30";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.NetAnalyzers";
    version = "6.0.0";
    sha256 = "06zy947m5lrbwb684g42ijb07r5jsqycvfnphc6cqfdrfnzqv6k9";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.2.0";
    sha256 = "0znah6arbcqari49ymigg3wiy2hgdifz8zsq8vdc3ynnf45r7h0c";
  })
  (fetchNuGet {
    pname = "Microsoft.Net.Http.Headers";
    version = "2.2.0";
    sha256 = "0w6lrk9z67bcirq2cj2ldfhnizc6id77ba6i30hjzgqjlyhh1gx5";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "16.9.60";
    sha256 = "0dbhm4n3fhfa55gpisgl3vxfc29a47hi47sqvqn5qxd7484bciyn";
  })
  (fetchNuGet {
    pname = "NStack.Core";
    version = "0.17.1";
    sha256 = "18xf6zcllmzsz3dx77igdrr4239n8bwdk8i7nkrdrn8b1jnq0nxi";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "0.44.0";
    sha256 = "0vsyvcmrg6k7938a3fqchynwkrcyipcgwl9i18hmimwihv8x0l4f";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.0";
    sha256 = "1ywfqn4md6g3iilpxjn5dsr0f5lx6z0yvhqp4pgjcamygg73cz2c";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.1";
    sha256 = "0f07d7hny38lq9w69wx4lxkn4wszrqf9m9js6fh9is645csm167c";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.1";
    sha256 = "1xcrjx5fwg284qdnxyi2d0lzdm5q4frlpkp0nf6vvkx1kdz2prrf";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "4.5.0";
    sha256 = "0srd5bva52n92i90wd88pzrqjsxnfgka3ilybwh7s6sf469y5s53";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    sha256 = "00k8ja51d0f9wrq4vv5z2jhq8hy31kac2rg0rv06prylcybzl8cy";
  })
  (fetchNuGet {
    pname = "Terminal.Gui";
    version = "1.7.2";
    sha256 = "187dz9vfwjs2n3lak7zjr0njihmvxdiwx9128kjasdgw883kdpma";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.2.14";
    sha256 = "15awsgyha0h1gnjnsciqvih53igh7x9fr09vjwbxydkm3r7na7sb";
  })
  (fetchNuGet {
    pname = "Wcwidth";
    version = "1.0.0";
    sha256 = "02i3m8vrpanzj1h4n8zj4dnd3cndx6cmg36n9qj56waa18d6mqy1";
  })
]
