# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "AsyncFixer";
    version = "1.6.0";
    hash = "sha256-8MWfDkTyotnouLwZASK27lM32NoGCLPLr4sBBqPkJFI=";
  })
  (fetchNuGet {
    pname = "ByteSize";
    version = "2.1.1";
    hash = "sha256-ZPiO0zdDX3F9QkQLWLbkyeicRZZoOGnS5vo55RttS2w=";
  })
  (fetchNuGet {
    pname = "Devlooped.SponsorLink";
    version = "0.10.5";
    hash = "sha256-m+eCuL8ifD/PJkyA70okbWYIDcp8ZV6mtDvnbthz6DQ=";
  })
  (fetchNuGet {
    pname = "ErrorProne.NET.Structs";
    version = "0.1.2";
    hash = "sha256-B0kzqe24j0+X96JCtQWXZK3aWfFAYKIYvhrMePMfgPI=";
  })
  (fetchNuGet {
    pname = "HexMate";
    version = "0.0.3";
    hash = "sha256-pA/wUH3+1CIXNmvpwedOOtfGA5uEMeis3XbSArol8r4=";
  })
  (fetchNuGet {
    pname = "Intellenum";
    version = "1.0.0-beta.3";
    hash = "sha256-FdLXSwxvQNyZWjFjJnUvuk1LAxPvuch557w0qHvmdfw=";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2022.1.0";
    hash = "sha256-AgCfhDvBb/xOLxNvFoZPYuiSBWEhXihHTBvYqLS+WFM=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.WebUtilities";
    version = "2.2.0";
    hash = "sha256-UdfOwSWqOUXdb0mGrSMx6Z+d536/P+v5clSRZyN5QTM=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.BannedApiAnalyzers";
    version = "3.3.4";
    hash = "sha256-YPTHTZ8xRPMLADdcVYRO/eq3O9uZjsD+OsGRZE+0+e8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    hash = "sha256-Enknv2RsFF68lEPdrf5M+BpV1kHoLTVRApKUwuk/pj0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.2.0";
    hash = "sha256-DMCTC3HW+sHaRlh/9F1sDwof+XgvVp9IzAqzlZWByn4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Net.Http.Headers";
    version = "2.2.0";
    hash = "sha256-pb8AoacSvy8hGNGodU6Lhv1ooWtUSCZwjmwd89PM1HA=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "16.9.60";
    hash = "sha256-1ke2CCKndVws3lgfEuEhKgnm+h706XhfKcpBNyypcDU=";
  })
  (fetchNuGet {
    pname = "NStack.Core";
    version = "0.17.1";
    hash = "sha256-sVuArQwL2dzytCei2fhCNg1Bcm4vntPb+PpXStk3rqM=";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "0.44.0";
    hash = "sha256-jlDQ0YaR11ghCjFR/tiNnuXJrYcMu6HQSGealyvbXm8=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.0";
    hash = "sha256-THw2znu+KibfJRfD7cE3nRYHsm7Fyn5pjOOZVonFjvs=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.1";
    hash = "sha256-7JhQNSvE6JigM1qmmhzOX3NiZ6ek82R4whQNb+FpBzg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.1";
    hash = "sha256-Lucrfpuhz72Ns+DOS7MjuNT2KWgi+m4bJkg87kqXmfU=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "4.5.0";
    hash = "sha256-o+jikyFOG30gX57GoeZztmuJ878INQ5SFMmKovYqLWs=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    hash = "sha256-niH6l2fU52vAzuBlwdQMw0OEoRS/7E1w5smBFoqSaAI=";
  })
  (fetchNuGet {
    pname = "Terminal.Gui";
    version = "1.7.2";
    hash = "sha256-qt42B0L8Na3kRCKkzmPru8IoLcjyn6nosEJL7nb67aA=";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.2.14";
    hash = "sha256-Sx9lTx51Nt8XlzuB7FI/8MVRYNw4Mm2lfQECBf3TXJU=";
  })
  (fetchNuGet {
    pname = "Wcwidth";
    version = "1.0.0";
    hash = "sha256-weNqGgpKcVMkTtaMV5npzbLRbCPyI0tgkN+qmzeqIwo=";
  })
]
