["async"]
cve = ["CVE-2021-43138"]
comment = "False positives"

["avahi"]
cve = ["CVE-2021-26720", "CVE-2021-3468"]
comment = "Attack vector is not applicable in nixOS setting &/OR DoS flaw"

["bind"]
cve = [
    "CVE-2019-6470",
    "CVE-2022-2795",
    "CVE-2022-2881",
    "CVE-2022-2906",
    "CVE-2022-3080",
]
comment = "True positive, however package is soon to be scoped to microVMs only"

["bolt"]
cve = [
    "CVE-2017-16754",
    "CVE-2019-15483",
    "CVE-2019-15484",
    "CVE-2019-15485",
    "CVE-2019-9185",
    "CVE-2020-28925",
    "CVE-2020-4040",
    "CVE-2020-4041",
    "CVE-2021-27367",
    "CVE-2022-31321",
]
comment = "False positives"

["cereal"]
cve = ["CVE-2020-11104", "CVE-2020-11105"]
comment = "False positives"

["charset"]
cve = ["CVE-2017-16098"]
comment = "False positives"

["cookie"]
cve = ["CVE-2017-18589"]
comment = "False positives"

["djvulibre"]
cve = [
    "CVE-2021-32490",
    "CVE-2021-32491",
    "CVE-2021-32492",
    "CVE-2021-32493",
    "CVE-2021-3500",
]
until = "2022-12-31"
comment = "True positives, minimal risk and no upstream nixpkgs fixes yet"

["dnsmasq"]
cve = [
    "CVE-2021-45951",
    "CVE-2021-45952",
    "CVE-2021-45953",
    "CVE-2021-45954",
    "CVE-2021-45955",
    "CVE-2021-45956",
    "CVE-2021-45957",
]
until = "2022-12-31"
comment = "True positives, CVE is currently marked as disputed and no upstream nixpkgs fixes yet"

["dpkg"]
cve = ["CVE-2022-1664"]
until = "2022-12-31"
comment = "True positives minimal risk due to build paradigm of nix"

["faad2"]
cve = [
    "CVE-2021-32273",
    "CVE-2021-32274",
    "CVE-2021-32276",
    "CVE-2021-32277",
    "CVE-2021-32278",
]
until = "2022-12-31"
comment = "True positives, no upstream fixes in nixpkgs yet"

["ffmpeg"]
cve = ["CVE-2021-38291"]
until = "2022-10-31"
comment = "Information does not link to explicit version, requires more investigation"

["gcc"]
cve = ["CVE-2018-12886", "CVE-2021-37322"]
until = "2022-10-31"
comment = "True positive, minimal risk due to build paradigm of nix"

["git"]
cve = [
    "CVE-2018-1000110",
    "CVE-2018-1000182",
    "CVE-2019-1003010",
    "CVE-2020-2136",
    "CVE-2021-21684",
    "CVE-2022-30947",
    "CVE-2022-30948",
    "CVE-2022-30949",
    "CVE-2022-36882",
    "CVE-2022-36883",
    "CVE-2022-36884",
    "CVE-2022-38663",
    "CVE-2022-31012",
]
comment = "False positives"

["glibc"]
cve = ["CVE-2021-3998"]
comment = "True positive, low severity and risk"

["go"]
cve = [
    "CVE-2021-29923",
    "CVE-2021-38297",
    "CVE-2021-39293",
    "CVE-2021-41771",
    "CVE-2021-41772",
    "CVE-2021-44716",
    "CVE-2021-44717",
    "CVE-2022-1705",
    "CVE-2022-1962",
    "CVE-2022-23772",
    "CVE-2022-23773",
    "CVE-2022-23806",
    "CVE-2022-24675",
    "CVE-2022-24921",
    "CVE-2022-27664",
    "CVE-2022-28131",
    "CVE-2022-28327",
    "CVE-2022-2879",
    "CVE-2022-2880",
    "CVE-2022-29526",
    "CVE-2022-29804",
    "CVE-2022-30580",
    "CVE-2022-30629",
    "CVE-2022-30630",
    "CVE-2022-30631",
    "CVE-2022-30632",
    "CVE-2022-30633",
    "CVE-2022-30634",
    "CVE-2022-30635",
    "CVE-2022-32148",
    "CVE-2022-32189",
    "CVE-2022-41715",
]
comment = "False positives"

["gradle"]
cve = [
    "CVE-2019-11065",
    "CVE-2019-15052",
    "CVE-2019-16370",
    "CVE-2020-11979",
    "CVE-2021-29428",
    "CVE-2021-29429",
    "CVE-2021-32751",
]
comment = "True positive, low risk"

["http-client"]
cve = ["CVE-2020-11021"]
comment = "False positives"

["lapack"]
cve = ["CVE-2021-4048"]
comment = "Build time dependency"

["lens"]
cve = ["CVE-2021-23154", "CVE-2021-44458"]
comment = "False positives"

["libde265"]
cve = [
    "CVE-2021-35452",
    "CVE-2021-36408",
    "CVE-2021-36409",
    "CVE-2021-36410",
    "CVE-2021-36411",
]
until = "2022-10-31"
comment = "True positive, no upstream fixes in nixpkgs yet, minimal risk due to firewalling"

["libmad"]
cve = ["CVE-2018-7263"]
until = "2022-10-31"
comment = "True positive, no upstream fixes in nixpkgs yet, minimal risk due to firewalling"

["libpng"]
cve = ["CVE-2017-12652"]
comment = "True positive, low risk"

["libtiff"]
cve = [
    "CVE-2022-0561",
    "CVE-2022-0562",
    "CVE-2022-0891",
    "CVE-2022-0908",
    "CVE-2022-1354",
    "CVE-2022-1355",
    "CVE-2022-2867",
    "CVE-2022-2868",
    "CVE-2022-2869",
    "CVE-2022-2953",
]
comment = "True positive, low risk"

["libvncserver"]
cve = ["CVE-2020-29260"]
comment = "True positive, low risk"

["linux-pam"]
cve = ["CVE-2022-28321"]
comment = "False positive; applicable to SUSE Tumbleweed"

["lua"]
cve = [
    "CVE-2020-15888",
    "CVE-2020-15945",
    "CVE-2020-15888",
    "CVE-2020-15945",
    "CVE-2021-43519",
]
comment = "True positive, build time dependency, risk accept"

["mujs"]
cve = ["CVE-2017-5627", "CVE-2017-5628", "CVE-2022-30974", "CVE-2022-30975"]
comment = "True positive, build time dependency, risk accept"

["network"]
cve = [
    "CVE-2021-35047",
    "CVE-2021-35048",
    "CVE-2021-35049",
    "CVE-2021-35050",
    "CVE-2022-0486",
    "CVE-2022-0997",
    "CVE-2022-24388",
    "CVE-2022-24389",
    "CVE-2022-24390",
    "CVE-2022-24391",
    "CVE-2022-24392",
    "CVE-2022-24393",
    "CVE-2022-24394",
]
comment = "False positives"

["npm"]
cve = ["CVE-2022-29244"]
comment = "Low risk due to how npm is utilised"

["nss"]
cve = ["CVE-2021-43527"]
comment = "False positive - ESR version utilised"

["oh-my-zsh"]
cve = ["CVE-2021-3727"]
comment = "False positive - Plugin not utilised"

["openexr"]
cve = [
    "CVE-2021-23169",
    "CVE-2021-23215",
    "CVE-2021-26260",
    "CVE-2021-26945",
    "CVE-2021-3598",
    "CVE-2021-3605",
    "CVE-2021-3933",
]
until = "2022-12-31"
comment = "True positive but no fix in nixpkgs yet"

["openjpeg"]
cve = ["CVE-2021-29338", "CVE-2021-3575", "CVE-2022-1122"]
until = "2022-12-31"
comment = "True positive but no reachability / risk based on configuration"

["openssl"]
cve = ["CVE-2018-16395", "CVE-2022-3358"]
comment = "False positives and/or low risk"

["p7zip"]
cve = ["CVE-2017-17969", "CVE-2018-5996"]
comment = "True positive and low risk"

["python"]
cve = [
    "CVE-2017-17522",
    "CVE-2017-18207",
    "CVE-2019-9674",
    "CVE-2021-23336",
    "CVE-2021-3733",
    "CVE-2022-0391",
    "CVE-2022-26488",
]
comment = "False positives"

["qemu"]
cve = ["CVE-2022-2962", "CVE-2022-3165"]
comment = "Flaw is pertinent to un-utilised feature"

["rubygems"]
cve = ["CVE-2022-36073"]
until = "2022-12-31"
comment = "True positive but no information on applicable packages yet"

["safe"]
cve = [
    "CVE-2019-11644",
    "CVE-2021-33594",
    "CVE-2021-33595",
    "CVE-2021-33596",
    "CVE-2021-40834",
    "CVE-2021-40835",
    "CVE-2021-44751",
    "CVE-2022-28868",
    "CVE-2022-28869",
    "CVE-2022-28870",
    "CVE-2022-28872",
    "CVE-2022-28873",
]
comment = "False positives"

["samba"]
cve = ["CVE-2021-3670", "CVE-2022-1615", "CVE-2022-32743"]
comment = "True positive, no fix upstream and minimal risk"

["SDL_ttf"]
cve = ["CVE-2022-27470"]
until = "2022-12-31"
comment = "True positive, no fix upstream and minimal risk"

["shellcheck"]
cve = ["CVE-2021-28794", "CVE-2018-7557"]
comment = "Deployed extension is suitable version for shellcheck"

["ShellCheck"]
cve = ["CVE-2021-28794", "CVE-2018-7557"]
comment = "Deployed extension is suitable version for shellcheck"

["subversion"]
cve = [
    "CVE-2017-1000085",
    "CVE-2018-1000111",
    "CVE-2020-2111",
    "CVE-2020-2304",
    "CVE-2021-21698",
    "CVE-2022-29046",
    "CVE-2022-29048",
]
comment = "False positives"

["tcl"]
cve = ["CVE-2021-35331"]
until = "2022-12-31"
comment = "Disputed CVE"

["unbound"]
cve = ["CVE-2022-3204"]
until = "2022-12-31"
comment = "False positive, software appears to be build-time dependency?"

["unzip"]
cve = ["CVE-2021-4217", "CVE-2022-0529", "CVE-2022-0530"]
comment = "True positive, build time dependency and/or ephemeral tool that also does not have enough information in CVE details"

["vim"]
cve = ["CVE-2022-3352"]
comment = "True positive, low risk"

["wolfssl"]
cve = ["CVE-2022-39173"]
comment = "True positive, build time dependency and/or ephemeral tool that also does not have enough information in CVE details"

["xar"]
cve = ["CVE-2017-11124", "CVE-2017-11125"]
comment = "True positive, build time dependency and/or ephemeral tool that also does not have enough information in CVE details"

["zip"]
cve = ["CVE-2018-13410"]
comment = "Disputed CVE with narrow exploitation case"

["zlib"]
cve = ["CVE-2018-25032", "CVE-2022-37434"]
comment = "False positive"
