{
  imports = [
    ../../modules/alacritty
    ../../modules/clamav
    ../../modules/direnv
    ../../modules/docker
    ../../modules/firefox
    ../../modules/fonts
    ../../modules/gnome
    ../../modules/gnupg
    ../../modules/lsd
    ../../modules/networking
    ../../modules/nix
    ../../modules/openssh
    ../../modules/pipewire
    ../../modules/starship
    ../../modules/rofi
    ../../modules/steam
    ../../modules/time
    ../../modules/timesyncd
    ../../modules/udev
    ../../modules/vscodium
    ../../modules/zsh
  ];
}
