{
  imports = [
    ../../modules/alacritty
    ../../modules/gnupg
    ../../modules/hardware/m1
    ../../modules/firefox
    ../../modules/fonts
    ../../modules/gnome
    ../../modules/lsd
    ../../modules/networking
    ../../modules/nix
    ../../modules/openssh
    ../../modules/starship
    ../../modules/time
    ../../modules/timesyncd
    ../../modules/udev
    ../../modules/vscodium
    ../../modules/zsh
  ];
}
