{ config, specialArgs, lib, options }:
let region = "ap-southeast";
in {
  # Piggybacks greatly off the following repositories awesome work: https://github.com/houstdav000/terranix-linode-poc
  # Thank you original author <3
  variable.LINODE_TOKEN = {
    type = "string";
    description = "Linode API token";
    nullable = false;
    sensitive = true;
  };

  terraform.required_providers.linode.source = "linode/linode";

  provider.linode.token = "\${ var.LINODE_TOKEN }";

  resource.linode_image.pidgey = let
    label = "pidgey";
    description = "Base image generated by nixos-generator";
    file_path = "${outputs.packages.x86_64-linux.pidgey-linode}/nixos.img.gz";
  in { inherit region label description file_path; };

  resource.linode_instance.pidgey = {
    inherit region;

    label = "pidgey";
    group = "nixos";
    tags = [ "nixos" ];
    type = "g6-nanode-1";
  };

  resource.linode_instance_disk.boot = {
    label = "boot";
    linode_id = "\${linode_instance.pidgey.id}";
    size = 25000;
    image = "\${linode_image.nixos.id}";
  };

  resource.linode_instance_disk.swap = {
    label = "swap";
    linode_id = "\${linode_instance.pidgey.id}";
    size = 512;
    filesystem = "swap";
  };

  resource.linode_instance_config.my-config = {
    linode_id = "\${linode_instance.pidgey.id}";
    label = "boot_config";
    booted = true;
    kernel = "linode/grub2";

    helpers = {
      devtmpfs_automount = false;
      distro = false;
      modules_dep = false;
      network = false;
      updatedb_disabled = false;
    };

    root_device = "/dev/sda";

    devices = {
      sda.disk_id = "\${linode_instance_disk.boot.id}";
      sdb.disk_id = "\${linode_instance_disk.swap.id}";
    };

    interface = [{ purpose = "public"; }];
  };
}
