# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "AsyncFixer";
    version = "1.6.0";
    sha256 = "0li4wjihc0cbmz5v6206vbc3flzfnqi026dwp3ldk8pj8h79zigh";
  })
  (fetchNuGet {
    pname = "ByteSize";
    version = "2.1.1";
    sha256 = "0v2bdldyafgswv96jf38jr2rrs69wjv5h2s489yp2ps36z9qxy34";
  })
  (fetchNuGet {
    pname = "Devlooped.SponsorLink";
    version = "0.10.5";
    sha256 = "0d78fgc6xrrvnjk5wrbwr86hhrkd4i5fz02c4v7kyz12pyw85rwv";
  })
  (fetchNuGet {
    pname = "ErrorProne.NET.Structs";
    version = "0.1.2";
    sha256 = "1wl03zrpik0spqca4q20y5cxmbb4jw2vahm2yyblz3xqxnlk6j87";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2022.1.0";
    sha256 = "0lsqpssain0v9i3jhpi1c42r5s329y31cvqk5x7gqvy17f29y002";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.BannedApiAnalyzers";
    version = "3.3.4";
    sha256 = "1vzrni7n94f17bzc13lrvcxvgspx9s25ap1p005z6i1ikx6wgx30";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.NetAnalyzers";
    version = "6.0.0";
    sha256 = "06zy947m5lrbwb684g42ijb07r5jsqycvfnphc6cqfdrfnzqv6k9";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j";
  })
  (fetchNuGet {
    pname = "Microsoft.IO.RecyclableMemoryStream";
    version = "2.2.0";
    sha256 = "0naw1ray9iqqr74qssx254zlh51wflg20vpk3q5jjkcihidzhvxa";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "16.9.60";
    sha256 = "0dbhm4n3fhfa55gpisgl3vxfc29a47hi47sqvqn5qxd7484bciyn";
  })
  (fetchNuGet {
    pname = "NStack.Core";
    version = "0.17.1";
    sha256 = "18xf6zcllmzsz3dx77igdrr4239n8bwdk8i7nkrdrn8b1jnq0nxi";
  })
  (fetchNuGet {
    pname = "Polly";
    version = "7.2.3";
    sha256 = "1iws4jd5iqj5nlfp16fg9p5vfqqas1si0cgh8xcj64y433a933cv";
  })
  (fetchNuGet {
    pname = "Spectre.Console.Analyzer";
    version = "0.44.0";
    sha256 = "0vsyvcmrg6k7938a3fqchynwkrcyipcgwl9i18hmimwihv8x0l4f";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.5";
    sha256 = "12fg196sdq3gcjcz365kypfkkmdrprpcw2fvjnww9jqa4yn8v99l";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    sha256 = "00k8ja51d0f9wrq4vv5z2jhq8hy31kac2rg0rv06prylcybzl8cy";
  })
  (fetchNuGet {
    pname = "Terminal.Gui";
    version = "1.7.2";
    sha256 = "187dz9vfwjs2n3lak7zjr0njihmvxdiwx9128kjasdgw883kdpma";
  })
  (fetchNuGet {
    pname = "ThisAssembly.AssemblyInfo";
    version = "1.2.14";
    sha256 = "15awsgyha0h1gnjnsciqvih53igh7x9fr09vjwbxydkm3r7na7sb";
  })
  (fetchNuGet {
    pname = "Wcwidth";
    version = "1.0.0";
    sha256 = "02i3m8vrpanzj1h4n8zj4dnd3cndx6cmg36n9qj56waa18d6mqy1";
  })
]
