{
  imports = [
    ../../modules/alacritty
    ../../modules/clamav
    ../../modules/fonts
    ../../modules/gnupg
    ../../modules/hardware/raspberry-pi-4
    ../../modules/lorri
    ../../modules/lsd
    ../../modules/networking
    ../../modules/nix
    ../../modules/openssh
    ../../modules/starship
    ../../modules/time
    ../../modules/xfce
    ../../modules/vscodium
    ../../modules/zsh
  ];
}
